### ISSUE TITLE
Where to wrap testnet WETH guide?

### ISSUE THREAD

**Issue by MrCleanerPickerUpper** [raiden-network/awesome-raiden#6]
1. Request Ether from:
Ropsten: https://faucet.ropsten.be/
Rinkeby: https://faucet.rinkeby.io/
Kovan: https://faucet.kovan.network/
Goerli: https://faucet.goerli.mudit.blog/

2. Wrap Ether:
https://0x.org/portal/weth

3. Connect wallet (ie Meta Mask) to:
https://lightclient.raiden.network/

4. Hubs for testing (on going list):
0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
......

**Comment by franzihei** [comment]
@mat7ias could you look into this?

**Comment by mat7ias** [comment]
@franzihei there was something along those lines in the [dApp testing section](https://github.com/mat7ias/awesome-raiden-old#dapp-testing) of the old Awesome Raiden. It was taken out shortly after merge to Raiden org. Do you mean something similar, just repurposed focusing on wrapping ETH and put in around the faucets section? If so, should it include info on Goerli wrapping? 0x and RadarRelay don't support wrapping on Goerli yet so we'd need to include [the contract](https://goerli.etherscan.io/address/0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6#writeContract). Another option would be to ask 0x if they can start supporting it.

I like the idea of having reliable "Hubs for testing". Although 0x5257964E is more just a hub I've invited a few people who've voiced interest to quickly test out the light client, it's unreliable since I play with it a bit to try things out. Might have to be a separate topic and discussion from a WETH guide whether to setup permanent hubs for testing.
